server:
  service_name: "user_service"
  host: localhost
  port: 8887
  log_level: "debug"

database:
  host: localhost
  port: 3306
  username: "042"
  password: "123123"
  dbname: "seckill_user"  
  charset: utf8mb4
  parseTime: true
  loc: UTC
