# 订单服务配置

# kitex服务器配置
server:
  service_name: "order_service"
  host: "127.0.0.1"
  port: 8889
  log_level: "debug"

# 活动服务的RPC
activity_rpc:
  host: "127.0.0.1"
  port: 8888
  timeout: 1000 #毫秒

#数据库配置
database:
  host: localhost
  port: 3306
  username: "042"
  password: "123123"
  dbname: "seckill_activity"
  charset: utf8mb4
  parseTime: true
  loc: UTC

# Redis配置
redis:
  host: localhost
  port: 6379
  password: "123123"
  db: 1
  pool_size: 100

# MQ配置
mq:
  type: "rabbitmq"
  rabbitmq:
    host: localhost
    port: 5672
    user: "042"
    password: "123123"
    exchange_name: "seckill_exchange"
    queue_name: "order_queue"
    routing_key: "order.create"
