# 活动服务配置

# kitex服务器配置
server:
  service_name: "activity_service"
  host: "127.0.0.1"
  port: 8888
  log_level: "debug"

#数据库配置
database:
  host: localhost
  port: 3306
  username: "042"
  password: "123123"
  dbname: "seckill_activity"  
  charset: utf8mb4
  parseTime: true
  loc: UTC

# Redis配置
redis:
  host: localhost
  port: 6379
  password: "123123"
  db: 0
  pool_size: 100
  