# Hertz 服务器配置
server:
  host: localhost
  port: 8080
  log_level: debug

activity_rpc:
  service_name: "activity_service"
  target_host: localhost
  target_port: 8888
  timeout: 1000   # ms

order_rpc:
  service_name: "order_service"
  target_host: localhost
  target_port: 8889
  timeout: 1000

redis:
  host: localhost
  port: 6379
  password: "123123"
  db: 2
